[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "functing"
version = "0.5.0"
description = "A tiny compositional execution engine for Python with HTML rendering support."
readme = "README.md"
requires-python = ">=3.10"
license = { text = "MIT" }
authors = [
    { name = "Profesor Hrbolek" }
]
keywords = [
    "composition",
    "asyncio",
    "templating",
    "html",
    "functional-programming",
]

classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

dependencies = []

[project.urls]
Homepage = "https://github.com/hrbolek/functing"
Repository = "https://github.com/hrbolek/functing"
Issues = "https://github.com/hrbolek/functing/issues"

[tool.setuptools]
packages = ["functing"]
